export enum NachrichtenCode {
    NEUER_MITSPIELER = "NEUER_MITSPIELER",
    LOBBYZEIT_ABGELAUFEN = "LOBBYZEIT_ABGELAUFEN",
    BEITRETEN_FEHLGESCHLAGEN = "BEITRETEN_FEHLGESCHLAGEN",
    SCHON_BEIGETRETEN = "SCHON_BEIGETRETEN",
    LOBBY_GESTARTET = "LOBBY_GESTARTET",
    LOBBY_VOLL = "LOBBY_VOLL"
}
