export enum NachrichtenCode {
    NEUER_MITSPIELER = "NEUER_MITSPIELER",
    LOBBYZEIT_ABGELAUFEN = "LOBBYZEIT_ABGELAUFEN",
    MITSPIELER_VERLAESST = "MITSPIELER_VERLAESST",
    BEITRETEN_FEHLGESCHLAGEN = "BEITRETEN_FEHLGESCHLAGEN",
    SCHON_BEIGETRETEN = "SCHON_BEIGETRETEN",
    LOBBY_GESTARTET = "LOBBY_GESTARTET",
    LOBBY_VOLL = "LOBBY_VOLL",
    COUNTDOWN_GESTARTET = "COUNTDOWN_GESTARTET",
    KEINE_LOBBY_FREI = "KEINE_LOBBY_FREI"
}
